version: '3.8'
services:
    pontue.laravel:
        container_name: pontue.laravel
        working_dir: /var/www/app
        build:
            context: docker
            dockerfile: Dockerfile
            args:
                user: admin
                uid: 1000
        image: php:8.2-fpm
        volumes:
            - .:/var/www/app
        networks:
            - pontue
        depends_on:
            - pontue.mariadb
            - pontue.installation
    pontue.nginx:
        container_name: pontue.nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
            - 443:443
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - pontue
        depends_on:
            - pontue.laravel
    pontue.installation:
        container_name: pontue.installation
        image: composer
        volumes:
            - ./:/app
        command: composer install
    pontue.mariadb:
        container_name: pontue.mariadb
        image: 'mariadb:10'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - ./docker/database/mariadb:/var/lib/mysql
        networks:
            - pontue
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    pontue:
        driver: bridge
